//! Cloudflare IP allowlist config generation.
//!
//! Fetches live Cloudflare IP ranges and writes an nginx `allow` directive
//! config file, refreshed at most once every 24 hours.

use anyhow::Result;
use std::fs;
use std::io::Write;
use std::time::Duration;

/// Generate cloudflare.conf with live Cloudflare IP ranges.
/// Fetches the latest IPs from Cloudflare's API and writes them to a config file.
pub fn generate_cloudflare_ips_config(paths: &crate::config::RikuPaths) -> Result<()> {
    let cloudflare_conf_path = paths.riku_root.join("cloudflare.conf");

    if !needs_refresh(&cloudflare_conf_path) {
        return Ok(());
    }

    let mut config_content = build_cloudflare_config()?;

    // Add SSH_CLIENT IP handling
    config_content.push_str("\n# Allow SSH client IP if available\n");
    config_content.push_str(
        "if ($remote_addr !~ ^($|192\\.168\\.|10\\.|172\\.(1[6-9]|2[0-9]|3[0-1])\\.) ) {\n",
    );
    config_content.push_str("    set $remote_addr $http_cf_connecting_ip;\n");
    config_content.push_str("}\n");

    // Write the config file
    let mut file = fs::File::create(&cloudflare_conf_path)?;
    file.write_all(config_content.as_bytes())?;

    crate::util::echo(
        &format!(
            "-----> Updated Cloudflare IP config ({} bytes)",
            config_content.len()
        ),
        "green",
    );

    Ok(())
}

/// Returns true if the cloudflare config file is missing or older than 24 hours.
fn needs_refresh(path: &std::path::Path) -> bool {
    if !path.exists() {
        return true;
    }
    if let Ok(metadata) = fs::metadata(path) {
        if let Ok(modified) = metadata.modified() {
            if let Ok(elapsed) = modified.elapsed() {
                return elapsed.as_secs() > 86400; // 24 hours
            }
        }
    }
    true
}

/// Fetch Cloudflare IPv4 and IPv6 ranges and return nginx allow directives.
fn build_cloudflare_config() -> Result<String> {
    let ipv4_url = "https://www.cloudflare.com/ips-v4";
    let ipv6_url = "https://www.cloudflare.com/ips-v6";

    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(10))
        .build()?;

    let mut content = String::new();
    content.push_str("# Cloudflare IP ranges - auto-generated by Riku\n");
    content.push_str("# Do not edit manually - will be refreshed every 24 hours\n\n");

    for (label, url) in [("IPv4", ipv4_url), ("IPv6", ipv6_url)] {
        if let Ok(response) = client.get(url).send() {
            if let Ok(ips) = response.text() {
                for ip in ips.lines() {
                    let ip = ip.trim();
                    if ip.is_empty() {
                        continue;
                    }
                    if is_valid_cidr(ip) {
                        content.push_str(&format!("allow {};\n", ip));
                    } else {
                        tracing::warn!("skipping invalid Cloudflare {} entry: {:?}", label, ip);
                    }
                }
            }
        }
    }

    Ok(content)
}

/// Returns true if the string looks like a valid IPv4/IPv6 CIDR or address.
/// Only permits characters that appear in valid IP/CIDR notation to prevent
/// a compromised upstream response from injecting nginx directives.
fn is_valid_cidr(line: &str) -> bool {
    let valid_chars = line
        .chars()
        .all(|c| c.is_ascii_hexdigit() || c == '.' || c == ':' || c == '/');
    valid_chars && (line.contains('.') || line.contains(':')) && !line.contains(' ')
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_valid_cidr_ipv4() {
        assert!(is_valid_cidr("192.168.1.0/24"));
    }

    #[test]
    fn test_is_valid_cidr_ipv4_single() {
        assert!(is_valid_cidr("10.0.0.1"));
    }

    #[test]
    fn test_is_valid_cidr_ipv6() {
        assert!(is_valid_cidr("2400:cb00::/32"));
    }

    #[test]
    fn test_is_valid_cidr_rejects_spaces() {
        assert!(!is_valid_cidr("192.168.1.0/24 allow all"));
    }

    #[test]
    fn test_is_valid_cidr_rejects_semicolons() {
        assert!(!is_valid_cidr("192.168.1.1; deny all"));
    }

    #[test]
    fn test_is_valid_cidr_rejects_empty() {
        assert!(!is_valid_cidr(""));
    }

    #[test]
    fn test_is_valid_cidr_rejects_no_dot_or_colon() {
        assert!(!is_valid_cidr("12345"));
    }

    #[test]
    fn test_is_valid_cidr_rejects_newline_injection() {
        assert!(!is_valid_cidr("192.168.1.0/24\ndeny all"));
    }

    #[test]
    fn test_needs_refresh_returns_true_for_missing_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("nonexistent.conf");
        assert!(needs_refresh(&path));
    }

    #[test]
    fn test_needs_refresh_returns_false_for_fresh_file() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("cloudflare.conf");
        std::fs::write(&path, "# fresh").unwrap();
        // File was just created — should NOT need refresh
        assert!(!needs_refresh(&path));
    }
}
